name: tuxfishing
base: core22
version: '1.0'
license: GPL-2.0-only
summary: 3D Fishing Game
description: |
  3D Fishing with 55 species of fish!
  Mouse = Rotate Camera, Scroll = Zoom Camera
  W,A / Arrows = Move Rod Cast Direction
  Space = Cast Rod, the higher the rod when you release space the farther the lure launches.
  Once you catch a fish keep hitting space to keep the rod up to reel it in.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  tuxfishing:
    extensions: [gnome]
    command: tuxfishing
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  tuxfishing:
    source: https://github.com/mrbid/tuxfishing
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2
